#!/usr/bin/env bash
# Transfers a file from our client to a server using scp command in this bash script
if [ "$#" -ne 4 ];
then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

path_to_local_file="$1"
remote_host="$2"
remote_username="$3"
ssh_private_key="$4"
path_to_remote_directory="~/"

scp -o StrictHostKeyChecking=no -i {{ssh_private_key}} {{path_to_local_file}} {{remote_username}}@{{remote_host}}:{{path_to_remote_directory}}
