#!/usr/bin/env bash
# Install Nginx, amke it listen to port 80 and welcoming page should display Hello World
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx restart
