#!/usr/bin/env bash
# redirection 301 - Moved Permanently”
# format - sed -i s/"string_to_replace"/"${new_string}"/g $file
old_string="location / {"
string_replace="location / redirect_me {\nreturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;"
sed -i 's/"${old_string}"/"${string_replace}"/g' /etc/nginx/sites-enabled/default
