#!/usr/bin bash
# redirection 301 - Moved Permanently”
# sed -i s/"string_to_replace"/"${new_string}"/g $file

sed -i s/"location / {"/"${location / redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;}"/g $/etc/nginx/sites-enabled/default
