#!/usr/bin/env bash
# redirection 301 - Moved Permanently”
# format - sed -i s/"string_to_replace"/"${new_string}"/g $file
sudo apt-get update
sudo apt upgrade
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/" /etc/nginx/sites-available/default
sudo service nginx reload
