#!/usr/bin/env bash
# redirection 301 - Moved Permanently”
# format - sed -i s/"string_to_replace"/"${new_string}"/g $file
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
old_string="location"
string_replace="location / redirect_me {\nreturn 301 https://www.google.com;"
sudo sed -i 's/"${old_string}"/"${string_replace}"/g' /etc/nginx/sites-enabled/default
service nginx restart
