#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt update
sudo apt install -y haproxy
content="frontend my_web\n\tbind *:80\n\tdefault_backend web_servers\n\nbackend web_servers\n\tbalance roundrobin\n\tserver 359699-web-01 18.204.20.181:80 check\n\tserver 359699-web-02 52.91.128.238:80 check"
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
echo "${content}" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy enable
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo service haproxy reload
