#!/usr/bin/env bash
# Prints 1 to 20 with some country supertitous bad luck number
i=1
while((i <= 20))
do
	if ((i == 4)); then
	echo "bad luck from China"
	elif ((i == 9)); then
	echo "bad luck from Japan"
	elif ((i == 17)); then
	echo "bad luck from Italy"
	else
	echo $i
	fi
	((i++))
done
