#!/usr/bin/env bash
#configures an Ubuntu server; localhost resolves to 127.0.0.2, facebook.com resolves to 8.8.8.8
cp /etc/hosts /etc/hosts.old
sed -i 's/127.0.0.1\tlocalhost/127.0.0.2 localhost\n8.8.8.8.8 facebook.com/' /etc/hosts.old
cp /etc/hosts.old /etc/hosts
